### ISSUE TITLE
How many epochs for IRN ?

### ISSUE THREAD

**Issue by abeardear** [jiwoon-ahn/irn#10]
I have train CAM for 5 epochs and get 48.3 miou,
but map and miou is low for sem_seg and ins_seg, when I train it 3 epochs.

Every thing not changed except I modify train_irn.py in line40,
model = torch.nn.DataParallel(model).cuda()

**Comment by jiwoon-ahn** [comment]
Hi @xiongzihua. I think your question overlaps with this [thread](https://github.com/jiwoon-ahn/irn/issues/4). Please check the link.
