### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by yassouali** [jiwoon-ahn/irn#14]
Hi, first of all, thanks for the amazing work

I was wandering if you intend to provide pretrained models, mainly cam reset and Irnet

thanks

**Comment by GrassBro** [comment]
Hi, @yassouali ,

I also want the pre-trained models of those two, the CAM ResNet and the IRNet. Do you already have that? Can you share a cope with me?

Thanks.

**Comment by yassouali** [comment]
Hi,

I trained mine, for cam Resnet it doesn't take that much time, less than an hour in 2 GPUs, for IRnet a little bit more but not much. If you could I advise to just trained them.

**Comment by GrassBro** [comment]
> Hi,
> 
> I trained mine, for cam Resnet it doesn't take that much time, less than an hour in 2 GPUs, for IRnet a little bit more but not much. If you could I advise to just trained them.

I am able to train them, but I cannot get the same result shown in the paper. I wonder to know the performance you achieved? Could you tell me how much mAP you get.

Thanks.
