### ISSUE TITLE
comparation with Affinity

### ISSUE THREAD

**Issue by mt-cly** [jiwoon-ahn/irn#19]
Hi,
In train_irn step, I remove the dispalce loss part and remains only boundary loss. 
I notice boundary loss is similar to the AffinityNet which you published in CVPR18 even the detail has some differents. But the semantic mIoU only 37+% which is even worse than CAM result(50%)，comared to Affinity result(59%)。
So I confuse the reason for such gap in same idea, similar  loss. Have you some suggests? THX

**Comment by jiwoon-ahn** [comment]
The displacement loss has no effect on the process of generating semantic segmentation masks. Perhaps, you have mistaken mAP with mIOU?

**Comment by mt-cly** [comment]
> The displacement loss has no effect on the process of generating semantic segmentation masks. Perhaps, you have mistaken mAP with mIOU?

I am sorry, I found the reason of that cause some wrong operations, and the isolated boundary loss would help semantic mIoU achive about 67% as well. thanks for reply.
