### ISSUE TITLE
How to process test data?

### ISSUE THREAD

**Issue by mt-cly** [jiwoon-ahn/irn#23]
Hi,
For train/val data, CAMs firstly filter  by GT classification labels, then get final segmentation by argmax after norming remained CAMs.
But How to handle with test data? Should I generate test classification label to do similar filter? or multiply cls probabilty with corresponding CAM?

**Comment by jiwoon-ahn** [comment]
Hi @mt-cly!
We did not evaluate the quality of pseudo segmentation labels on the test set.
You can still use and test DeepLab or Mask R-CNN trained with the pseudo labels of the train set.

**Comment by mt-cly** [comment]
Thank you for reply. May be what I said is not clear.
I notice that in inferring step, approach use a file named 'cls_labels.npy' which is generated by analysing .xml of annotation, so I wonder about:
1. Is it appropriate that infering train/val segmentation with the help of classification GT?
2. How to get the classification label of test data, in other words, how can I make a 'cls_labels.npy' for test data without avaliable '.xml' ?
Thanks~

**Comment by jiwoon-ahn** [comment]
1. We do not infer segmentation results with the help of GT.
2. We can't and shouldn't.
We do make pseudo segmentation labels with image-level GT labels. However, this is not the final goal. For inference, you must have your own Mask R-CNN or other segmentation networks.
Please read the intro section of our paper for more information.

**Comment by mt-cly** [comment]
Oh!!! I get it, the purpose of approach is not getting final segmentation but to generate pseudo labels, and I should use those perseudo labels to train a new model with fully-supervised.
I apologize for my careless. Thanks.
