### ISSUE TITLE
deeplab-v2 and CRF

### ISSUE THREAD

**Issue by arnike** [jiwoon-ahn/irn#24]
Hi Jiwoon,
the original deeplab-v2 with VGG16 and ResNet-101 have somewhat different architectures (e.g. design of ASPP module). I was wondering, in your implementation with ResNet-50, did you use ResNet-101 as the reference, or the VGG-based one? Also, from A.2 it seems that you used CRF to compute the upper bound. Did you also use CRF after fully-supervised training on the pseudo labels?
Thanks in advance,
Nikita

**Comment by jiwoon-ahn** [comment]
Hi @arnike,
Sorry for the late reply,
1) We set ResNet-101 as the reference, and reduced its depth to ResNet-50.
2) Yes, we did so because the original DeepLab v2 employed dCRF.
