### ISSUE TITLE
COCO training code

### ISSUE THREAD

**Issue by rodrigob** [jiwoon-ahn/irn#25]
"Training code for MS-COCO" is on the TODOs. 
Any plans to release this code soonish so as to include in ECCV2020 experiments ?

**Comment by jiwoon-ahn** [comment]
Hi @rodrigob,
Sorry for the late reply. Unfortunately, I cannot release the code until we publish the paper. :(

**Comment by rodrigob** [comment]
Is there a timeline for the paper publishing/Coco training release ?
