### ISSUE TITLE
path index

### ISSUE THREAD

**Issue by GrassBro** [jiwoon-ahn/irn#3]
Hi, Jiwoon Ahn,

I wonder to know what is the path index in the code? which part in the paper could I refer to it?

Additionally, when will the training detail be released? Looking forward to following your work.

Thanks.

**Comment by jiwoon-ahn** [comment]
Hi, @TinyGrass 

PathIndex gathers all indices of pixels lying on the straight line between a pair of two coordinates. From these coordinates, we encourage or penalize boundary scores. (Please refer to Sec.4.2 and Eq.7.)
Sorry for missing the deadline I set. I've assigned to other things to do. I'll update the repository no later than the end of this week. :(

**Comment by GrassBro** [comment]
> Hi, @TinyGrass
> 
> PathIndex gathers all indices of pixels lying on the straight line between a pair of two coordinates. From these coordinates, we encourage or penalize boundary scores. (Please refer to Sec.4.2 and Eq.7.)
> Sorry for missing the deadline I set. I've assigned to other things to do. I'll update the repository no later than the end of this week. :(

Thank you for your consideration. Best.
