### ISSUE TITLE
About 'x = x[0] + x[1].flip(-1)' in resnet50_cam.py.

### ISSUE THREAD

**Issue by ZhuPeipei-CUHKSZ-TJUTCM** [jiwoon-ahn/irn#32]
What is the meaning or function of 'x = x[0] + x[1].flip(-1)' ?

**Comment by SCoulY** [comment]
Hi @username123062,
I had same question about this line, did u figured this out?

**Comment by chenslcool** [comment]
I think, it corresponding to what VOC12ClassificationDatasetMSF.__get_item__ do to img, matbe a way to generate CAM better

**Comment by Elaineok** [comment]
x[0] represents the original image, x[1] represents the horizontal flip.

x[1].flip(-1) represents the flipped image will be flipped back again.  Multi-scale is often used to obtain better CAM, here is the flip
