### ISSUE TITLE
Performance is poor after re-train a Mask RCNN

### ISSUE THREAD

**Issue by bityangke** [jiwoon-ahn/irn#6]
Hi,
I took the instance-level pseudo labels generated by running `make_ins_seg_labels.py' and kept the instance mask whose score is higher than 0.
Then, I transfered these labels from *.npy to cocostyle json annotation and trained the standard Mask R-CNN with ResNet-50-FPN.
However, the performance I've get is:

![image](https://user-images.githubusercontent.com/7546216/60759364-b4a73780-a056-11e9-9a32-2033dcdb27d4.png)

**Specifically, box mAP of AP50 is 45.8, segmentation mAP of AP50 is 22.6.**
I noticed that the instance number in pseudo label is about 2/3 of the gt instance number for `train_aug' set.
Did I miss something to reimplement the performance of Mask R-CNN with pseudo label? 

Thanks a lot!

**Comment by jiwoon-ahn** [comment]
Hi @bityangke,
It is hard to give you a straight-forward answer to your question. Coco mask annotation is composed of polygons, not pixel-wise instance labels. Hence, there are many ways of transfering the psuedo labels for mask rcnn. Please make sure you did not make any mistakes during the conversion process.
Plus, the mask rcnn should be pretrained on imagenet.

**Comment by bityangke** [comment]
Thanks very much！

**Comment by discretecoder** [comment]
@bityangke did you fix this issue? do you have a code for label transformations? thanks
