### ISSUE TITLE
About the L_fg^D loss

### ISSUE THREAD

**Issue by dongzhang89** [jiwoon-ahn/irn#7]
Thank you for the very good work!
I have a question about the L_fg^D loss, in section 4.3, why the difference of (i, j) in D denotes D(x_i)-D(x_j) rather than  D(x_j)-D(x_i)?
I'm very confused about this point, looking forward to your reply. 
Thank you very much

**Comment by jiwoon-ahn** [comment]
It's simple, x_i + D(x_i) = x_j + D(x_j) must hold. Then, x_j - x_i = D(x_i) - D(x_j) follows.

**Comment by dongzhang89** [comment]
OK, thank you very much!
